# changing port number
server:
  port: 9094

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9093
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

      # Write a SQL query beautifully on console
      properties:
        hibernate:
          format_sql: true

# Logging the SQL queries
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

