# changing port number
server:
  port: 9093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

      # Write a SQL query beautifully on console
      properties:
        hibernate:
          format_sql: true

# Logging the SQL queries
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

